#!/usr/bin/env python3
"""Build data/team-seasons.js from the generated per-player stat files.

This produces a franchise -> season -> roster index so the web app can show,
for any team and year, exactly which players were on the roster and classify
them (key players / supporting cast / young & growth) WITHOUT any API calls.

It reads only local files (data/players/*.json) -- no network required. Re-run
it whenever you've downloaded more players with generate-players.py:

    python tools/build-team-seasons.py

Output shape (keyed by stable NBA TEAM_ID, which matches data/teams.js ids):

    window.NBA.teamSeasons = {
      "1610612747": {            // franchise id (Lakers)
        "2010": [                // season END year
          {"id":977,"name":"Kobe Bryant","gp":73,"min":33.9,"pts":27.0,
           "reb":5.4,"ast":4.7,"stl":1.5,"blk":0.3,"exp":14},
          ...
        ]
      }
    }
"""

import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")
PLAYERS_DIR = os.path.join(DATA_DIR, "players")


def num(v, d=1):
    try:
        return round(float(v), d)
    except (TypeError, ValueError):
        return None


def main():
    files = glob.glob(os.path.join(PLAYERS_DIR, "*.json"))
    teams = {}  # teamId(str) -> { yearStr -> [entries] }
    n_players = 0

    for path in files:
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            continue
        seasons = data.get("seasons") or []
        regular = [s for s in seasons if s.get("type") != "playoffs"]
        years = [s.get("season") for s in regular if s.get("season")]
        if not years:
            continue
        debut = min(years)
        n_players += 1

        for s in regular:
            year = s.get("season")
            team_id = s.get("teamId")
            abbr = s.get("teamAbbr")
            if not year or not team_id or abbr in (None, "", "TOT"):
                continue
            entry = {
                "id": data.get("id"),
                "name": data.get("name"),
                "gp": s.get("gp"),
                "min": num(s.get("min")),
                "pts": num(s.get("pts")),
                "reb": num(s.get("reb")),
                "ast": num(s.get("ast")),
                "stl": num(s.get("stl")),
                "blk": num(s.get("blk")),
                "exp": year - debut,
            }
            teams.setdefault(str(team_id), {}).setdefault(str(year), []).append(entry)

    # Sort each roster by minutes played (desc) so the app can rank easily.
    for tid in teams:
        for yr in teams[tid]:
            teams[tid][yr].sort(key=lambda e: (e["min"] or 0, e["pts"] or 0), reverse=True)

    out_path = os.path.join(DATA_DIR, "team-seasons.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/build-team-seasons.py. Do not edit by hand.\n")
        f.write("// Franchise (NBA TEAM_ID) -> season end year -> roster with per-game averages.\n")
        f.write("window.NBA = window.NBA || {};\n")
        f.write("window.NBA.teamSeasons = ")
        json.dump(teams, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    total_team_years = sum(len(v) for v in teams.values())
    print("Indexed %d players across %d franchises and %d team-seasons."
          % (n_players, len(teams), total_team_years))
    print("Wrote %s" % out_path)


if __name__ == "__main__":
    main()
